version: '2'

services:
  waf:
    image: amioranza/naxsi
    hostname: naxsi
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
    depends_on:
      - elasticsearch
    networks:
        - waf-naxsi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - ./nginx/sites-enabled/app-01:/etc/nginx/sites-enabled/app-01
      - ./nginx/sites-enabled/app-02:/etc/nginx/sites-enabled/app-02
      - ./nginx/sites-enabled/app-03:/etc/nginx/sites-enabled/app-03
      - ./naxsi_core.rules:/etc/naxsi/naxsi_core.rules
      - ./naxsi_whitelist.rules:/etc/naxsi/naxsi_whitelist.rules
      - ./collectd.conf:/etc/collectd/collectd.conf

  app-01:
    image: ghost:alpine
    hostname: ghost
    restart: always
    networks:
      - waf-naxsi
    volumes:
      - ghost_data:/var/lib/ghost/content

  app-02:
    image: jenkins:alpine
    hostname: jenkins
    restart: always
    networks:
      - waf-naxsi
    volumes:
      - jenkins_data:/var/jenkins_home/

  app-03:
    image: redmine
    hostname: redmine
    restart: always
    networks:
      - waf-naxsi
    volumes:
      - redmine_data:/usr/src/redmine

  elasticsearch:
    image: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - waf-naxsi
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana
    hostname: kibana
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kbndata:/usr/share/kibana/data
    networks:
      - waf-naxsi
    ports:
      - "5601:5601"

  logstash:
    image: logstash:alpine
    hostname: logstash
    restart: always
    command: ["-f", "/home/logstash/logstash.conf"]
    volumes:
      - ./logstash:/home/logstash
      - lstdata:/usr/share/logstash/data
    networks:
      - waf-naxsi
    ports:
      - "514:5140/tcp"
      - "514:5140/udp"

volumes:
  esdata:
  kbndata:
  lstdata:
  ghost_data:
  jenkins_data:
  redmine_data:

networks:
  waf-naxsi:
    driver: bridge
    ipam:
      config:
      - subnet: 10.157.57.0/24
